In [1]:
import pandas as pd
import numpy as np

In [6]:
data = pd.read_csv("movie_metadata.csv")
data.head() #head of data

movie_code  duration  facenumber_in_poster country       budget  \
0           1     178.0                   0.0     USA  237000000.0   
1           2     169.0                   0.0     USA  300000000.0   
2           3     148.0                   1.0      UK  245000000.0   
3           4     164.0                   0.0     USA  250000000.0   
4           5     132.0                   1.0     USA  263700000.0   

         gross  num_voted_users  num_user_for_reviews  num_critic_for_reviews  \
0  760505847.0           886204                3054.0                   723.0   
1  309404152.0           471220                1238.0                   302.0   
2  200074175.0           275868                 994.0                   602.0   
3  448130642.0          1144337                2701.0                   813.0   
4   73058679.0           212204                 738.0                   462.0   

   movie_facebook_likes  director_facebook_likes  actor_1_facebook_likes  \
0                 33000                      0.0                  1000.0   
1                     0                    563.0                 40000.0   
2                 85000                      0.0                 11000.0   
3                164000                  22000.0                 27000.0   
4                 24000                    475.0                   640.0   

   actor_2_facebook_likes  actor_3_facebook_likes  cast_total_facebook_likes  \
0                   936.0                   855.0                       4834   
1                  5000.0                  1000.0                      48350   
2                   393.0                   161.0                      11700   
3                 23000.0                 23000.0                     106759   
4                   632.0                   530.0                       1873   

   imdb_score imdb_score_class  
0         7.9             Good  
1         7.1             Good  
2         6.8             Good  
3         8.5        Excellent  
4         6.6             Good

In [7]:
data.describe() #statistika deskriptif

movie_code     duration  facenumber_in_poster        budget  \
count  5042.000000  5028.000000           5029.000000  4.551000e+03   
mean   2521.500000   107.201074              1.371446  3.975262e+07   
std    1455.644359    25.197441              2.013683  2.061149e+08   
min       1.000000     7.000000              0.000000  2.180000e+02   
25%    1261.250000    93.000000              0.000000  6.000000e+06   
50%    2521.500000   103.000000              1.000000  2.000000e+07   
75%    3781.750000   118.000000              2.000000  4.500000e+07   
max    5042.000000   511.000000             43.000000  1.221550e+10   

              gross  num_voted_users  num_user_for_reviews  \
count  4.159000e+03     5.042000e+03           5022.000000   
mean   4.846841e+07     8.368475e+04            272.770808   
std    6.845299e+07     1.384940e+05            377.982886   
min    1.620000e+02     5.000000e+00              1.000000   
25%    5.340988e+06     8.599250e+03             65.000000   
50%    2.551750e+07     3.437100e+04            156.000000   
75%    6.230944e+07     9.634700e+04            326.000000   
max    7.605058e+08     1.689764e+06           5060.000000   

       num_critic_for_reviews  movie_facebook_likes  director_facebook_likes  \
count             4993.000000           5042.000000              4938.000000   
mean               140.194272           7527.457160               686.621709   
std                121.601675          19322.070537              2813.602405   
min                  1.000000              0.000000                 0.000000   
25%                 50.000000              0.000000                 7.000000   
50%                110.000000            166.000000                49.000000   
75%                195.000000           3000.000000               194.750000   
max                813.000000         349000.000000             23000.000000   

       actor_1_facebook_likes  actor_2_facebook_likes  actor_3_facebook_likes  \
count             5035.000000             5029.000000             5020.000000   
mean              6561.323932             1652.080533              645.009761   
std              15021.977635             4042.774685             1665.041728   
min                  0.000000                0.000000                0.000000   
25%                614.500000              281.000000              133.000000   
50%                988.000000              595.000000              371.500000   
75%              11000.000000              918.000000              636.000000   
max             640000.000000           137000.000000            23000.000000   

       cast_total_facebook_likes   imdb_score  
count                5042.000000  5042.000000  
mean                 9700.959143     6.442007  
std                 18165.101925     1.125189  
min                     0.000000     1.600000  
25%                  1411.250000     5.800000  
50%                  3091.000000     6.600000  
75%                 13758.750000     7.200000  
max                656730.000000     9.500000

In [8]:
np.sum(data.isnull()) #number of NA for each variable

movie_code                     0
duration                      14
facenumber_in_poster          13
country                        4
budget                       491
gross                        883
num_voted_users                0
num_user_for_reviews          20
num_critic_for_reviews        49
movie_facebook_likes           0
director_facebook_likes      104
actor_1_facebook_likes         7
actor_2_facebook_likes        13
actor_3_facebook_likes        22
cast_total_facebook_likes      0
imdb_score                     0
imdb_score_class               0
dtype: int64

In [10]:
data['budget']=data['budget'].fillna(3.975262e+07)
np.sum(data.isnull())

movie_code                     0
duration                      14
facenumber_in_poster          13
country                        4
budget                         0
gross                        883
num_voted_users                0
num_user_for_reviews          20
num_critic_for_reviews        49
movie_facebook_likes           0
director_facebook_likes      104
actor_1_facebook_likes         7
actor_2_facebook_likes        13
actor_3_facebook_likes        22
cast_total_facebook_likes      0
imdb_score                     0
imdb_score_class               0
dtype: int64

In [ ]:
() #apabila variabel terdapat lebih dari 15% missing value dapat dijadikan kandidat untuk dihapus
# jika missing value <10% variabel tersebut tidak dihapus
# jika missing value sebesar 50% maka variabel tersebut dihapus

In [11]:
data['gross']=data['gross'].fillna(4.846841e+07)
np.sum(data.isnull())

movie_code                     0
duration                      14
facenumber_in_poster          13
country                        4
budget                         0
gross                          0
num_voted_users                0
num_user_for_reviews          20
num_critic_for_reviews        49
movie_facebook_likes           0
director_facebook_likes      104
actor_1_facebook_likes         7
actor_2_facebook_likes        13
actor_3_facebook_likes        22
cast_total_facebook_likes      0
imdb_score                     0
imdb_score_class               0
dtype: int64

In [15]:
from scipy.stats import mode

data['budget']=data['budget'].fillna(data['budget'].mean())
data['actor_1_facebook_likes']=data['actor_1_facebook_likes'].fillna(data['actor_1_facebook_likes'].mean())
data['actor_2_facebook_likes']=data['actor_2_facebook_likes'].fillna(data['actor_2_facebook_likes'].mean())
data['director_facebook_likes']=data['director_facebook_likes'].fillna(data['director_facebook_likes'].mean())
data['facenumber_in_poster']=data['facenumber_in_poster'].fillna(data['facenumber_in_poster'].mean())
data['country']=data['country'].fillna(data['country']).dropna().mode()[0]
data['num_user_for_reviews']=data['num_user_for_reviews'].fillna(data['num_user_for_reviews'].mean())
data['num_critic_for_reviews']=data['num_critic_for_reviews'].fillna(data['num_critic_for_reviews'].mean())
data['actor_3_facebook_likes']=data['actor_3_facebook_likes'].fillna(data['actor_3_facebook_likes'].mean())
np.sum(data.isnull())

movie_code                   0
duration                     0
facenumber_in_poster         0
country                      0
budget                       0
gross                        0
num_voted_users              0
num_user_for_reviews         0
num_critic_for_reviews       0
movie_facebook_likes         0
director_facebook_likes      0
actor_1_facebook_likes       0
actor_2_facebook_likes       0
actor_3_facebook_likes       0
cast_total_facebook_likes    0
imdb_score                   0
imdb_score_class             0
dtype: int64

In [22]:
from scipy import stats
z = np.abs(stats.zscore(data._get_numeric_data()))
print(z)
data = data[(z<3).all(axis=1)]
print(data.shape)

[[2.14664144 0.47400948 1.76781095 ... 0.1708808  0.42036772 1.71484259]
 [2.13613022 1.20161154 0.87848976 ... 1.19373652 0.67544007 1.92594585]
 [2.07681691 2.76712696 0.88571071 ... 0.54454396 0.47901647 1.23714804]
 ...
 [1.5728288  0.98119464 0.88571071 ... 0.03877766 0.36052611 1.43394742]
 [1.5743304  1.7087967  0.87848976 ... 1.23902902 0.81440779 0.05635179]
 [1.57583201 0.78275771 0.87848976 ... 1.17863901 0.78200187 0.35155085]]
(2396, 16)


In [24]:
data

movie_code    duration  facenumber_in_poster      budget        gross  \
97            98  120.000000              0.000000  39752620.0   48468410.0   
198          199  107.201074              1.000000  39752620.0   48468410.0   
203          204  120.000000              0.000000  39752620.0   48468410.0   
241          242  116.000000              1.000000  78000000.0   48468410.0   
323          324  110.000000              0.000000  10000000.0   10200000.0   
366          367  141.000000              2.000000  39752620.0   48468410.0   
376          377  128.000000              1.000000  80000000.0   72515360.0   
380          381  116.000000              0.000000  68000000.0   61355436.0   
389          390  129.000000              0.000000  20000000.0   37567440.0   
415          416  130.000000              1.000000  70000000.0   50016394.0   
421          422  123.000000              0.000000  39752620.0   48468410.0   
424          425  135.000000              0.000000  60000000.0   31111260.0   
429          430  130.000000              0.000000   8000000.0   48468410.0   
465          466   88.000000              1.000000  80000000.0   90443603.0   
466          467   93.000000              0.000000  65000000.0   82226474.0   
468          469  135.000000              1.000000  75000000.0   76081498.0   
470          471   98.000000              2.000000  70000000.0   74329966.0   
471          472   80.000000              0.000000  80000000.0  100169068.0   
472          473   83.000000              0.000000  80000000.0   73215310.0   
473          474  102.000000              1.000000  80000000.0   80360866.0   
474          475  130.000000              0.000000  80000000.0   69102910.0   
476          477  117.000000              0.000000  39752620.0     821997.0   
479          480   74.000000              0.000000  80000000.0   60507228.0   
483          484  129.000000              1.000000  75000000.0   45356386.0   
488          489   81.000000              0.000000  39752620.0   48468410.0   
489          490  117.000000              2.000000  39752620.0   27779888.0   
491          492  145.000000              1.000000  80000000.0   34566746.0   
493          494   87.000000              0.000000  80000000.0   36073232.0   
495          496   91.000000              4.000000  80000000.0   20950820.0   
496          497  118.000000              4.000000  80000000.0   19673424.0   
...          ...         ...                   ...         ...          ...   
5005        5006   89.000000              0.000000     60000.0   48468410.0   
5006        5007   93.000000              4.000000  39752620.0       9609.0   
5008        5009   65.000000              1.000000     27000.0       8231.0   
5009        5010   85.000000              1.000000  39752620.0   48468410.0   
5010        5011   97.000000              0.000000     25000.0    2856622.0   
5011        5012  109.000000              3.000000  35000000.0   10499968.0   
5012        5013   79.000000              0.000000     24000.0   48468410.0   
5014        5015  100.000000              0.000000     23000.0    1227508.0   
5015        5016   90.000000              2.000000     25000.0   48468410.0   
5016        5017   90.000000              1.000000     22000.0   48468410.0   
5018        5019   91.000000              0.000000  39752620.0   48468410.0   
5020        5021   85.000000              0.000000     15000.0     192467.0   
5021        5022   60.000000              0.000000     15000.0   48468410.0   
5022        5023   88.000000              2.000000     15000.0      76382.0   
5023        5024   78.000000              0.000000     20000.0   48468410.0   
5024        5025  108.000000              2.000000     10000.0     180483.0   
5025        5026  110.000000              1.000000      4500.0     136007.0   
5026        5027   90.000000              0.000000     10000.0     673780.0   
5027        5028   83.000000              0.000000     1